/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'totalDeliveryBoys' : bigint,
  'activeOrders' : bigint,
  'onlineDeliveryBoys' : bigint,
  'totalEarnings' : bigint,
  'deliveredOrders' : bigint,
}
export interface DeliveryBoy {
  'id' : PersistentId,
  'password' : string,
  'name' : string,
  'isOnline' : boolean,
  'email' : string,
  'earnings' : bigint,
  'codCollected' : bigint,
  'phone' : string,
  'shiftId' : [] | [PersistentId],
}
export type LoginResult = {
    'ok' : { 'userId' : PersistentId, 'name' : string, 'role' : Role }
  } |
  { 'err' : string };
export interface Order {
  'id' : PersistentId,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryCharge' : bigint,
  'shopId' : PersistentId,
  'createdAt' : bigint,
  'deliveryBoyId' : [] | [PersistentId],
  'address' : string,
  'paymentType' : PaymentType,
  'phone' : string,
  'items' : string,
  'amount' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'delivering' : null } |
  { 'pending' : null } |
  { 'reached_shop' : null } |
  { 'going_to_shop' : null } |
  { 'picked' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export type PaymentType = { 'cod' : null } |
  { 'online' : null };
export type PersistentId = bigint;
export type Role = { 'admin' : null } |
  { 'shop' : null } |
  { 'delivery_boy' : null };
export interface Shift {
  'id' : PersistentId,
  'startTime' : string,
  'endTime' : string,
  'name' : string,
  'maxUsers' : bigint,
}
export interface ShiftBooking {
  'id' : PersistentId,
  'deliveryBoyId' : PersistentId,
  'shiftId' : PersistentId,
}
export interface Shop {
  'id' : PersistentId,
  'password' : string,
  'name' : string,
  'email' : string,
  'location' : string,
}
export interface UserProfile {
  'userId' : PersistentId,
  'name' : string,
  'role' : Role,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDeliveryBoy' : ActorMethod<
    [string, string, string, string],
    PersistentId
  >,
  'addShift' : ActorMethod<[string, string, string, bigint], PersistentId>,
  'addShop' : ActorMethod<[string, string, string, string], PersistentId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDeliveryBoy' : ActorMethod<[PersistentId, PersistentId], boolean>,
  'bookShift' : ActorMethod<[PersistentId, PersistentId], boolean>,
  'cancelShiftBooking' : ActorMethod<[PersistentId, PersistentId], boolean>,
  'createOrder' : ActorMethod<
    [PersistentId, string, string, string, string, PaymentType, bigint],
    PersistentId
  >,
  'deleteDeliveryBoy' : ActorMethod<[PersistentId], boolean>,
  'deleteShift' : ActorMethod<[PersistentId], boolean>,
  'deleteShop' : ActorMethod<[PersistentId], boolean>,
  'getBookingsForDeliveryBoy' : ActorMethod<
    [PersistentId],
    Array<ShiftBooking>
  >,
  'getBookingsForShift' : ActorMethod<[PersistentId], Array<ShiftBooking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDeliveryBoy' : ActorMethod<[PersistentId], [] | [DeliveryBoy]>,
  'getDeliveryBoys' : ActorMethod<[], Array<DeliveryBoy>>,
  'getDeliveryCharge' : ActorMethod<[], bigint>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersForDeliveryBoy' : ActorMethod<[PersistentId], Array<Order>>,
  'getOrdersForShop' : ActorMethod<[PersistentId], Array<Order>>,
  'getShifts' : ActorMethod<[], Array<Shift>>,
  'getShops' : ActorMethod<[], Array<Shop>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDeliveryBoyOnline' : ActorMethod<[PersistentId, boolean], boolean>,
  'setDeliveryCharge' : ActorMethod<[bigint], undefined>,
  'updateDeliveryBoy' : ActorMethod<
    [PersistentId, string, string, string],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[PersistentId, OrderStatus], boolean>,
  'updateShift' : ActorMethod<
    [PersistentId, string, string, string, bigint],
    boolean
  >,
  'updateShop' : ActorMethod<[PersistentId, string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];