/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PersistentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentType = IDL.Variant({
  'cod' : IDL.Null,
  'online' : IDL.Null,
});
export const ShiftBooking = IDL.Record({
  'id' : PersistentId,
  'deliveryBoyId' : PersistentId,
  'shiftId' : PersistentId,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'shop' : IDL.Null,
  'delivery_boy' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userId' : PersistentId,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalDeliveryBoys' : IDL.Nat,
  'activeOrders' : IDL.Nat,
  'onlineDeliveryBoys' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'deliveredOrders' : IDL.Nat,
});
export const DeliveryBoy = IDL.Record({
  'id' : PersistentId,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'email' : IDL.Text,
  'earnings' : IDL.Nat,
  'codCollected' : IDL.Nat,
  'phone' : IDL.Text,
  'shiftId' : IDL.Opt(PersistentId),
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'delivering' : IDL.Null,
  'pending' : IDL.Null,
  'reached_shop' : IDL.Null,
  'going_to_shop' : IDL.Null,
  'picked' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : PersistentId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryCharge' : IDL.Nat,
  'shopId' : PersistentId,
  'createdAt' : IDL.Int,
  'deliveryBoyId' : IDL.Opt(PersistentId),
  'address' : IDL.Text,
  'paymentType' : PaymentType,
  'phone' : IDL.Text,
  'items' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Shift = IDL.Record({
  'id' : PersistentId,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'name' : IDL.Text,
  'maxUsers' : IDL.Nat,
});
export const Shop = IDL.Record({
  'id' : PersistentId,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'location' : IDL.Text,
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({
    'userId' : PersistentId,
    'name' : IDL.Text,
    'role' : Role,
  }),
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDeliveryBoy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [PersistentId],
      [],
    ),
  'addShift' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [PersistentId],
      [],
    ),
  'addShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [PersistentId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDeliveryBoy' : IDL.Func([PersistentId, PersistentId], [IDL.Bool], []),
  'bookShift' : IDL.Func([PersistentId, PersistentId], [IDL.Bool], []),
  'cancelShiftBooking' : IDL.Func([PersistentId, PersistentId], [IDL.Bool], []),
  'createOrder' : IDL.Func(
      [
        PersistentId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PaymentType,
        IDL.Nat,
      ],
      [PersistentId],
      [],
    ),
  'deleteDeliveryBoy' : IDL.Func([PersistentId], [IDL.Bool], []),
  'deleteShift' : IDL.Func([PersistentId], [IDL.Bool], []),
  'deleteShop' : IDL.Func([PersistentId], [IDL.Bool], []),
  'getBookingsForDeliveryBoy' : IDL.Func(
      [PersistentId],
      [IDL.Vec(ShiftBooking)],
      ['query'],
    ),
  'getBookingsForShift' : IDL.Func(
      [PersistentId],
      [IDL.Vec(ShiftBooking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDeliveryBoy' : IDL.Func(
      [PersistentId],
      [IDL.Opt(DeliveryBoy)],
      ['query'],
    ),
  'getDeliveryBoys' : IDL.Func([], [IDL.Vec(DeliveryBoy)], ['query']),
  'getDeliveryCharge' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersForDeliveryBoy' : IDL.Func(
      [PersistentId],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOrdersForShop' : IDL.Func([PersistentId], [IDL.Vec(Order)], ['query']),
  'getShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
  'getShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDeliveryBoyOnline' : IDL.Func([PersistentId, IDL.Bool], [IDL.Bool], []),
  'setDeliveryCharge' : IDL.Func([IDL.Nat], [], []),
  'updateDeliveryBoy' : IDL.Func(
      [PersistentId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateOrderStatus' : IDL.Func([PersistentId, OrderStatus], [IDL.Bool], []),
  'updateShift' : IDL.Func(
      [PersistentId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateShop' : IDL.Func(
      [PersistentId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PersistentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentType = IDL.Variant({ 'cod' : IDL.Null, 'online' : IDL.Null });
  const ShiftBooking = IDL.Record({
    'id' : PersistentId,
    'deliveryBoyId' : PersistentId,
    'shiftId' : PersistentId,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'shop' : IDL.Null,
    'delivery_boy' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userId' : PersistentId,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalDeliveryBoys' : IDL.Nat,
    'activeOrders' : IDL.Nat,
    'onlineDeliveryBoys' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'deliveredOrders' : IDL.Nat,
  });
  const DeliveryBoy = IDL.Record({
    'id' : PersistentId,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'email' : IDL.Text,
    'earnings' : IDL.Nat,
    'codCollected' : IDL.Nat,
    'phone' : IDL.Text,
    'shiftId' : IDL.Opt(PersistentId),
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'delivering' : IDL.Null,
    'pending' : IDL.Null,
    'reached_shop' : IDL.Null,
    'going_to_shop' : IDL.Null,
    'picked' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : PersistentId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryCharge' : IDL.Nat,
    'shopId' : PersistentId,
    'createdAt' : IDL.Int,
    'deliveryBoyId' : IDL.Opt(PersistentId),
    'address' : IDL.Text,
    'paymentType' : PaymentType,
    'phone' : IDL.Text,
    'items' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Shift = IDL.Record({
    'id' : PersistentId,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'name' : IDL.Text,
    'maxUsers' : IDL.Nat,
  });
  const Shop = IDL.Record({
    'id' : PersistentId,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'location' : IDL.Text,
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({
      'userId' : PersistentId,
      'name' : IDL.Text,
      'role' : Role,
    }),
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDeliveryBoy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [PersistentId],
        [],
      ),
    'addShift' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [PersistentId],
        [],
      ),
    'addShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [PersistentId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDeliveryBoy' : IDL.Func(
        [PersistentId, PersistentId],
        [IDL.Bool],
        [],
      ),
    'bookShift' : IDL.Func([PersistentId, PersistentId], [IDL.Bool], []),
    'cancelShiftBooking' : IDL.Func(
        [PersistentId, PersistentId],
        [IDL.Bool],
        [],
      ),
    'createOrder' : IDL.Func(
        [
          PersistentId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PaymentType,
          IDL.Nat,
        ],
        [PersistentId],
        [],
      ),
    'deleteDeliveryBoy' : IDL.Func([PersistentId], [IDL.Bool], []),
    'deleteShift' : IDL.Func([PersistentId], [IDL.Bool], []),
    'deleteShop' : IDL.Func([PersistentId], [IDL.Bool], []),
    'getBookingsForDeliveryBoy' : IDL.Func(
        [PersistentId],
        [IDL.Vec(ShiftBooking)],
        ['query'],
      ),
    'getBookingsForShift' : IDL.Func(
        [PersistentId],
        [IDL.Vec(ShiftBooking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDeliveryBoy' : IDL.Func(
        [PersistentId],
        [IDL.Opt(DeliveryBoy)],
        ['query'],
      ),
    'getDeliveryBoys' : IDL.Func([], [IDL.Vec(DeliveryBoy)], ['query']),
    'getDeliveryCharge' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersForDeliveryBoy' : IDL.Func(
        [PersistentId],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersForShop' : IDL.Func([PersistentId], [IDL.Vec(Order)], ['query']),
    'getShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDeliveryBoyOnline' : IDL.Func([PersistentId, IDL.Bool], [IDL.Bool], []),
    'setDeliveryCharge' : IDL.Func([IDL.Nat], [], []),
    'updateDeliveryBoy' : IDL.Func(
        [PersistentId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateOrderStatus' : IDL.Func([PersistentId, OrderStatus], [IDL.Bool], []),
    'updateShift' : IDL.Func(
        [PersistentId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateShop' : IDL.Func(
        [PersistentId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };