/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Order {
    id: PersistentId;
    customerName: string;
    status: OrderStatus;
    deliveryCharge: bigint;
    shopId: PersistentId;
    createdAt: bigint;
    deliveryBoyId?: PersistentId;
    address: string;
    paymentType: PaymentType;
    phone: string;
    items: string;
    amount: bigint;
}
export type LoginResult = {
    __kind__: "ok";
    ok: {
        userId: PersistentId;
        name: string;
        role: Role;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface DeliveryBoy {
    id: PersistentId;
    password: string;
    name: string;
    isOnline: boolean;
    email: string;
    earnings: bigint;
    codCollected: bigint;
    phone: string;
    shiftId?: PersistentId;
}
export interface DashboardStats {
    totalOrders: bigint;
    pendingOrders: bigint;
    totalDeliveryBoys: bigint;
    activeOrders: bigint;
    onlineDeliveryBoys: bigint;
    totalEarnings: bigint;
    deliveredOrders: bigint;
}
export interface Shift {
    id: PersistentId;
    startTime: string;
    endTime: string;
    name: string;
    maxUsers: bigint;
}
export interface ShiftBooking {
    id: PersistentId;
    deliveryBoyId: PersistentId;
    shiftId: PersistentId;
}
export interface Shop {
    id: PersistentId;
    password: string;
    name: string;
    email: string;
    location: string;
}
export type PersistentId = bigint;
export interface UserProfile {
    userId: PersistentId;
    name: string;
    role: Role;
    email: string;
}
export enum OrderStatus {
    cancelled = "cancelled",
    delivering = "delivering",
    pending = "pending",
    reached_shop = "reached_shop",
    going_to_shop = "going_to_shop",
    picked = "picked",
    delivered = "delivered",
    accepted = "accepted"
}
export enum PaymentType {
    cod = "cod",
    online = "online"
}
export enum Role {
    admin = "admin",
    shop = "shop",
    delivery_boy = "delivery_boy"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDeliveryBoy(name: string, phone: string, email: string, password: string): Promise<PersistentId>;
    addShift(name: string, startTime: string, endTime: string, maxUsers: bigint): Promise<PersistentId>;
    addShop(name: string, location: string, email: string, password: string): Promise<PersistentId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignDeliveryBoy(orderId: PersistentId, deliveryBoyId: PersistentId): Promise<boolean>;
    bookShift(deliveryBoyId: PersistentId, shiftId: PersistentId): Promise<boolean>;
    cancelShiftBooking(deliveryBoyId: PersistentId, shiftId: PersistentId): Promise<boolean>;
    createOrder(shopId: PersistentId, customerName: string, phone: string, address: string, items: string, paymentType: PaymentType, amount: bigint): Promise<PersistentId>;
    deleteDeliveryBoy(id: PersistentId): Promise<boolean>;
    deleteShift(id: PersistentId): Promise<boolean>;
    deleteShop(id: PersistentId): Promise<boolean>;
    getBookingsForDeliveryBoy(deliveryBoyId: PersistentId): Promise<Array<ShiftBooking>>;
    getBookingsForShift(shiftId: PersistentId): Promise<Array<ShiftBooking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDeliveryBoy(id: PersistentId): Promise<DeliveryBoy | null>;
    getDeliveryBoys(): Promise<Array<DeliveryBoy>>;
    getDeliveryCharge(): Promise<bigint>;
    getOrders(): Promise<Array<Order>>;
    getOrdersForDeliveryBoy(deliveryBoyId: PersistentId): Promise<Array<Order>>;
    getOrdersForShop(shopId: PersistentId): Promise<Array<Order>>;
    getShifts(): Promise<Array<Shift>>;
    getShops(): Promise<Array<Shop>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    login(email: string, password: string): Promise<LoginResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDeliveryBoyOnline(id: PersistentId, isOnline: boolean): Promise<boolean>;
    setDeliveryCharge(amount: bigint): Promise<void>;
    updateDeliveryBoy(id: PersistentId, name: string, phone: string, email: string): Promise<boolean>;
    updateOrderStatus(orderId: PersistentId, status: OrderStatus): Promise<boolean>;
    updateShift(id: PersistentId, name: string, startTime: string, endTime: string, maxUsers: bigint): Promise<boolean>;
    updateShop(id: PersistentId, name: string, location: string, email: string): Promise<boolean>;
}
import type { DeliveryBoy as _DeliveryBoy, LoginResult as _LoginResult, Order as _Order, OrderStatus as _OrderStatus, PaymentType as _PaymentType, PersistentId as _PersistentId, Role as _Role, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDeliveryBoy(arg0: string, arg1: string, arg2: string, arg3: string): Promise<PersistentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeliveryBoy(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeliveryBoy(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addShift(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<PersistentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addShift(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShift(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addShop(arg0: string, arg1: string, arg2: string, arg3: string): Promise<PersistentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addShop(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShop(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDeliveryBoy(arg0: PersistentId, arg1: PersistentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDeliveryBoy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDeliveryBoy(arg0, arg1);
            return result;
        }
    }
    async bookShift(arg0: PersistentId, arg1: PersistentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.bookShift(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookShift(arg0, arg1);
            return result;
        }
    }
    async cancelShiftBooking(arg0: PersistentId, arg1: PersistentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelShiftBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelShiftBooking(arg0, arg1);
            return result;
        }
    }
    async createOrder(arg0: PersistentId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: PaymentType, arg6: bigint): Promise<PersistentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, to_candid_PaymentType_n3(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, to_candid_PaymentType_n3(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async deleteDeliveryBoy(arg0: PersistentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeliveryBoy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeliveryBoy(arg0);
            return result;
        }
    }
    async deleteShift(arg0: PersistentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShift(arg0);
            return result;
        }
    }
    async deleteShop(arg0: PersistentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShop(arg0);
            return result;
        }
    }
    async getBookingsForDeliveryBoy(arg0: PersistentId): Promise<Array<ShiftBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsForDeliveryBoy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsForDeliveryBoy(arg0);
            return result;
        }
    }
    async getBookingsForShift(arg0: PersistentId): Promise<Array<ShiftBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsForShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsForShift(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDeliveryBoy(arg0: PersistentId): Promise<DeliveryBoy | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryBoy(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryBoy(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryBoys(): Promise<Array<DeliveryBoy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryBoys();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryBoys();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryCharge(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryCharge();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryCharge();
            return result;
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersForDeliveryBoy(arg0: PersistentId): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForDeliveryBoy(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForDeliveryBoy(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersForShop(arg0: PersistentId): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForShop(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForShop(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShifts(): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShifts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShifts();
            return result;
        }
    }
    async getShops(): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShops();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShops();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setDeliveryBoyOnline(arg0: PersistentId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDeliveryBoyOnline(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDeliveryBoyOnline(arg0, arg1);
            return result;
        }
    }
    async setDeliveryCharge(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDeliveryCharge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDeliveryCharge(arg0);
            return result;
        }
    }
    async updateDeliveryBoy(arg0: PersistentId, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryBoy(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryBoy(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateOrderStatus(arg0: PersistentId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateShift(arg0: PersistentId, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShift(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShift(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateShop(arg0: PersistentId, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShop(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShop(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_DeliveryBoy_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryBoy): DeliveryBoy {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentType): PaymentType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeliveryBoy]): DeliveryBoy | null {
    return value.length === 0 ? null : from_candid_DeliveryBoy_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersistentId]): PersistentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PersistentId;
    password: string;
    name: string;
    isOnline: boolean;
    email: string;
    earnings: bigint;
    codCollected: bigint;
    phone: string;
    shiftId: [] | [_PersistentId];
}): {
    id: PersistentId;
    password: string;
    name: string;
    isOnline: boolean;
    email: string;
    earnings: bigint;
    codCollected: bigint;
    phone: string;
    shiftId?: PersistentId;
} {
    return {
        id: value.id,
        password: value.password,
        name: value.name,
        isOnline: value.isOnline,
        email: value.email,
        earnings: value.earnings,
        codCollected: value.codCollected,
        phone: value.phone,
        shiftId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.shiftId))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PersistentId;
    customerName: string;
    status: _OrderStatus;
    deliveryCharge: bigint;
    shopId: _PersistentId;
    createdAt: bigint;
    deliveryBoyId: [] | [_PersistentId];
    address: string;
    paymentType: _PaymentType;
    phone: string;
    items: string;
    amount: bigint;
}): {
    id: PersistentId;
    customerName: string;
    status: OrderStatus;
    deliveryCharge: bigint;
    shopId: PersistentId;
    createdAt: bigint;
    deliveryBoyId?: PersistentId;
    address: string;
    paymentType: PaymentType;
    phone: string;
    items: string;
    amount: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n20(_uploadFile, _downloadFile, value.status),
        deliveryCharge: value.deliveryCharge,
        shopId: value.shopId,
        createdAt: value.createdAt,
        deliveryBoyId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.deliveryBoyId)),
        address: value.address,
        paymentType: from_candid_PaymentType_n22(_uploadFile, _downloadFile, value.paymentType),
        phone: value.phone,
        items: value.items,
        amount: value.amount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _PersistentId;
    name: string;
    role: _Role;
}): {
    userId: PersistentId;
    name: string;
    role: Role;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _PersistentId;
    name: string;
    role: _Role;
    email: string;
}): {
    userId: PersistentId;
    name: string;
    role: Role;
    email: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    delivering: null;
} | {
    pending: null;
} | {
    reached_shop: null;
} | {
    going_to_shop: null;
} | {
    picked: null;
} | {
    delivered: null;
} | {
    accepted: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "delivering" in value ? OrderStatus.delivering : "pending" in value ? OrderStatus.pending : "reached_shop" in value ? OrderStatus.reached_shop : "going_to_shop" in value ? OrderStatus.going_to_shop : "picked" in value ? OrderStatus.picked : "delivered" in value ? OrderStatus.delivered : "accepted" in value ? OrderStatus.accepted : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    online: null;
}): PaymentType {
    return "cod" in value ? PaymentType.cod : "online" in value ? PaymentType.online : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        userId: _PersistentId;
        name: string;
        role: _Role;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        userId: PersistentId;
        name: string;
        role: Role;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n26(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    shop: null;
} | {
    delivery_boy: null;
}): Role {
    return "admin" in value ? Role.admin : "shop" in value ? Role.shop : "delivery_boy" in value ? Role.delivery_boy : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeliveryBoy>): Array<DeliveryBoy> {
    return value.map((x)=>from_candid_DeliveryBoy_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n18(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): _PaymentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: PersistentId;
    name: string;
    role: Role;
    email: string;
}): {
    userId: _PersistentId;
    name: string;
    role: _Role;
    email: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: to_candid_Role_n29(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    shop: null;
} | {
    delivery_boy: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.shop ? {
        shop: null
    } : value == Role.delivery_boy ? {
        delivery_boy: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    delivering: null;
} | {
    pending: null;
} | {
    reached_shop: null;
} | {
    going_to_shop: null;
} | {
    picked: null;
} | {
    delivered: null;
} | {
    accepted: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.delivering ? {
        delivering: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.reached_shop ? {
        reached_shop: null
    } : value == OrderStatus.going_to_shop ? {
        going_to_shop: null
    } : value == OrderStatus.picked ? {
        picked: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): {
    cod: null;
} | {
    online: null;
} {
    return value == PaymentType.cod ? {
        cod: null
    } : value == PaymentType.online ? {
        online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
